# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

[[main]]
  name = "Research"
  url = "#publications"
  weight = 2

[[main]]
  name = "Blog"
  identifier = "post"
  url = "post/"
  weight = 3

[[main]]
  name = "Courses"
  identifier = "courses"
  url = ""
  weight = 4

[[main]]
  name = "Econometrics for Research Students"
  parent = "courses"
  url = "https://github.com/matteocourthoud/Econometrics-for-Research-Students-2019"
  weight = 1

[[main]]
  name = "Machine Learning for Economic Analysis"
  parent = "courses"
  url = "https://github.com/matteocourthoud/Machine-Learning-for-Economic-Analysis-2020"
  weight = 2

[[main]]
  name = "Programming Practices for Research Students"
  parent = "courses"
  url = "https://pp4rs.github.io/"
  weight = 3

[[main]]
  name = "CV"
  url = "files/cv.pdf"
  weight = 5

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 6
