--- 
title: "Econometrics Notes"
author: "Matteo Courthoud"
date: "Last updated: `r Sys.Date()`"
biblio-style: apalike
link-citations: yes
colorlinks: yes
graphics: yes
lot: no
lof: no
fontsize: 12pt
description: "Econometrics Notes"
monofont: "Source Code Pro"
monofontoptions: "Scale=0.7"
site: bookdown::bookdown_site
---

# Preface {-}

Welcome to my lecture notes for PhD Econometrics! You can download the full PDF using the button at the top-left corner of the page. 

These notes were initially born as my personal summary for the PhD Econometrics course of professor [Damian Kozbur](https://www.econ.uzh.ch/en/people/faculty/kozbur.html) in Zurich. The first draft was the result of an intense collaborative effort together with Chiara Aina and Paolo Mengano. They helped a lot in both drafting and revising the original notes. During the years I have expanded the first draft in order to make it more comprehensive and include Matlab code examples. I will try to be as transparent as possible on the sources of the material but all errors are mine.

On the left, you can find the ordered table of contents. The first three lectures cover basics in [matrix algebra](#appendix1), [probability theory](#appendix2) and [large sample theory](#appendix3). The [fourth lecture](#lecture1) introduces the Gauss-Markov Model and the OLS estimator. The other lectures follow. At the end of each section, I will post some sample code in Matlab to replicate the main results. In a [separate page](#matlabcode) I have collected all the Matlab code present in the notes.

All comments are very welcome. If you want to suggest edits or signal typos (I know there are many), please let me know at [matteo.courthoud@econ.uzh.ch](mailto: matteo.courthoud@econ.uzh.ch). This webpage was created using [Bookdown](https://bookdown.org/yihui/rmarkdown/).



## References {-}

- Kozbur (2019), PhD Econometrics - Lecture Notes.
- Hansen (2019), "*[Econometrics](https://www.ssc.wisc.edu/~bhansen/econometrics/Econometrics.pdf)*".
- Wooldridge (2010), "*Econometric Analysis of Cross Section and Panel Data*".
- Greene (2006), "*Econometric Analysis*".
- Hayashi (2000), "*Econometrics*".